[project]
name = "fapi-er-u"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.17.1",
    "fastapi[standard]>=0.121.0",
    "sqlalchemy>=2.0.44",
]
